config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories
  resources :transactions
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'categories#index', as: :authenticated_root
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
    unauthenticated :user do
      root to: 'splash_screen#home', as: :unauthenticated_root
    end
  end
  root 'splash_screen#home'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, Category, author_id: user.id
      can :update, Category, author_id: user.id
      can :destroy, Category, author_id: user.id
      can :read, Transaction, author_id: user.id
      can :update, Transaction, author_id: user.id
      can :destroy, Transaction, author_id: user.id
      can :create, Category
      can :create, Transaction
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :transactions

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :category

  validates :name, presence: true
  validates :amount, presence: true, numericality: { money: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories, foreign_key: 'author_id', dependent: :destroy
  has_many :transactions, foreign_key: 'author_id', dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new; end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon, :author_id)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  def home; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_transaction, only: %i[show edit update destroy]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
    @recent_transactions = @transactions.order(created_at: :desc)
    @total_transactions = current_user.transactions.sum(:amount)
  end

  # GET /transactions/1 or /transactions/1.json
  def show
    @transaction = current_user.transactions.find(params[:id])
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_url(@transaction), notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:name, :amount, :author_id, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/splash_screen_helper.rb
module SplashScreenHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <div class="d-flex justify-content-between">
    <%= image_tag "#{category.icon}", size: "80x80", alt: 'icon' %>
    <div>
       <li><p class="d-flex align-items-center justify-content-between text_me"><%= category.name %></p></li>
      <span class="created_at"><%= category.created_at.strftime('%F - %I:%H:%M %p') %></span>
    </div>
    <div class="mt-3">
    <h6 class="total_at"> <%= number_to_currency(category.transactions.sum(:amount)) %></h6>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<section class="vh-100" style="background-color: #eee;">
  
  <div class="container h-90">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">


                <%= form_with(model: category) do |form| %>
                  <% if category.errors.any? %>
                    <div style="color: red">
                      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

                      <ul>
                        <% category.errors.each do |error| %>
                          <li><%= error.full_message %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>

                  <div>
                    <%= form.text_field :name, class:"form-control", placeholder: "Name" %>
                  </div>

                  <div>
                    <%= form.text_field :icon, class:"form-control mt-3 mb-3", placeholder: "Only valid image url" %>
                  </div>

                  <div>
                    <%= form.text_field :author_id, value: current_user.id, class:"form-control", placeholder: "Name", hidden: true %>
                  </div>

                  <div>
                    <%= form.submit "Add Category", class: "btn btn-primary form-control" %>
                  </div>
                <% end %>
             
                <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                  <%= link_to "Back to categories", categories_path %>
                </div>
              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= flash[:alert] %></p>

<div id="categories">
  <% @categories.each do |category| %>
    <% if can? :read, category %>
      <%= link_to category do %>
        <div class="card-1">
          <%= render category %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="d-flex gap-3">
  <%= link_to "New category", new_category_path, class: "btn bg-first text-white w-50" %>
  <%= link_to "New transaction", new_transaction_path, class: "btn bg-second text-white w-50" %>
</div>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="mx-4">
  <%= render @category %>

  <% if can? :update, @category %>
    <%= link_to "Edit this category", edit_category_path(@category), hidden: true %>
  <% end %>

  <%= link_to "Back to categories", categories_path, hidden: true %>

  <% if can? :destroy, @category %>
    <%= button_to "Destroy this category", @category, method: :delete, hidden: true %>
  <% end %>
</div>

<div>
  <% if @category.transactions.empty? %>
    <p>Add some transactions. There's none yet!</p>
  <% else %>
    <% @category.transactions.order(created_at: :desc).each do |transaction| %>
      <%= link_to transaction do %>
        <div class="card-1">
          <%= render transaction %>
        </div>
      <% end %>
    <% end %>
  <% end %>

  <div class="d-flex gap-3">
    <%= link_to "New transaction", new_transaction_path, class: "btn bg-second text-white w-100" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlanApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="/css/styles.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans&family=Black+Han+Sans&family=Lato:wght@100;300;700;900&family=Montserrat:wght@500;700;900&family=Poppins:ital,wght@0,200;0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,700&family=Roboto+Slab:wght@100;200;300;500;700;800&family=Shizuru&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
  </head>
  
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<% if controller_name != 'splash_screen' %>

  <nav class="navbar navbar-expand-xlg navbar-dark bg-first">
    <div class="container-fluid">
      <% unless "#{action_name.capitalize} #{controller_name.capitalize.singularize}" == "Index Category" || "#{action_name.capitalize} #{controller_name.capitalize.singularize}" == "Index Transaction" %>
        <%# <i class="bi bi-arrow-left text-white fs-4"></i> %>
        <%# <%= link_to "Back", "history.back()" %>
        <% if "#{action_name.capitalize} #{controller_name.capitalize.singularize}" == "New Transaction" %>
          <%= link_to 'javascript:history.back()' do %>
            <i class="bi bi-arrow-left text-white fs-4"></i> 
          <% end %>
        <% else %>
          <%= link_to root_path do %>
            <i class="bi bi-arrow-left text-white fs-4"></i> 
          <% end %>
        <% end %>        
      <% else %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% end %>
      <a class="navbar-brand" href="#">
        <% case "#{action_name.capitalize} #{controller_name.capitalize.singularize}" %>
        <% when "New Session" %>
          LOGIN
        <% when "New Registration" %>
          REGISTER
        <% when "New Password" %>
          RECOVER PASSWORD
        <% when "Show Category" %>
          SINGLE CATEGORY
        <% when "Index Category" %>
          CATEGORIES
        <% when "Index Transaction" %>
          TRANSACTIONS
        <% when "New Category" %>
          ADD NEW CATEGORIES
        <% when "New Transaction" %>
          ADD NEW TRANSACTIONS
        <% when "Show Transaction" %>
          SINGLE TRANSACTION
        <% else %>
          <%= controller_name.upcase.singularize %>
        <% end %>
      </a>
      <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <h2 class="mt-3 text-white">Welcome</h2>
            <hr class='text-white'>
            <h2 class="mt-2 text-white"><%= current_user.name %></h2>
            <hr class='text-white'>
            <li class="nav-item mt-2 d-flex flex-row">
            <li>
              <h2><%= link_to 'Home', root_path, class: "text-light" %></h2>
            </li>
            <li><i class="bi bi-house-heart text-white"></i></i></li>
            <hr class='text-white'>
            </li>
            <li class="nav-item mt-2">
            <li><h2><%= link_to 'Transactions', transactions_path, class: "text-light" %></h2></li>
            <li><i class="bi bi-wallet2 text-white"></i></li>
            <hr class='text-white'>
            </li>
            <li class="nav-item mt-2 fw-bold">
              <a><%= button_to "Log out", destroy_user_session_path, method: :delete, class: 'btn primary-color text-white fs-22' %></a></li>
              <hr class='text-white'>
            </li>
          </ul>
        </div>
      <% end %>
      <% case "#{action_name.capitalize} #{controller_name.capitalize.singularize}" %>
        <% when "New Session" %>
          <%= link_to "Login", session_path(resource_name), class: "text-white" %> 
        <% when "New Registration" %>
          <%= link_to "Next", session_path(resource_name), class: "text-white" %>
        <% when "Index Category" %>
          <i class="bi bi-search text-white"></i>
        <% when "Index Transaction" %>
          <i class="bi bi-search text-white fs-4"></i>
        <% else %>
          <p class="color-first"> </p>
      <% end %>
    </div>
  </nav>
  
<% end %>

app/views/splash_screen/home.html.erb
<div class="p-5">
  <div class="">
    <p style="color: red"><%= flash[:alert] %></p>
    <div class="d-flex justify-content-center">
      <%= image_tag '/assets/images/plan_app_demo_1.gif', size: "250x240", alt: 'icon', class: "justify-content-center" %>
    </div>
    <div class="d-grid gap-2 col-12 mx-auto">
      <%= link_to "Log in", new_user_session_path, class: "btn bg-first text-white hover-text-black" %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/transactions/_form.html.erb
<section class="vh-100" style="background-color: #eee;">
  
  <div class="container h-90">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <%= form_with(model: transaction) do |form| %>
                  <% if transaction.errors.any? %>
                  <div style="color: red">
                    <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

                    <ul>
                      <% transaction.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                      <% end %>
                    </ul>
                  </div>
                  <% end %>

                  <div>
                    <%#= form.label :name, style: "display: block" %>
                    <%= form.text_field :name, class:"form-control", placeholder: "Name"  %>
                  </div>

                  <div>
                    <%#= form.label :amount, style: "display: block" %>
                    <%= form.text_field :amount, class:"form-control mt-3 mb-3", placeholder: "Enter Amount" %>
                  </div>

                  <div>
                    <%#= form.label :author_id, style: "display: block" %>
                    <%= form.text_field :author_id, value: current_user.id, hidden: true %>
                  </div>

                  <div>
                    <%#= form.label :category_id, style: "display: block" %>
                    <div>
                      <%= form.select :category_id, current_user.categories.collect {|c| [c.name, c.id]}, { prompt: "Select Category" }, class:"form-control mb-3" %>
                    </div>
                  </div>

                  <div>
                    <%= form.submit "Add Transaction", class: "btn btn-primary form-control" %>
                  </div>
                <% end %>
                <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                  <%= link_to "Back to transactions", transactions_path %>
                </div>
              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <div class="d-flex justify-content-between">
    <%= image_tag "#{transaction.category.icon}", size: "80x80", alt: 'icon' %>
    <div>
      <li><p class="d-flex align-items-center justify-content-between text_me"><%= transaction.name %></p></li>
      <span class="created_at"><%= transaction.created_at.strftime('%F - %I:%M:%S %p') %></span>
    </div>
    <div class="mt-3">
    <h6 class="total_at"> <%= number_to_currency(transaction.amount) %></h6>
    </div>
  </div>
</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "" do  %>
  <div class="d-flex gap-3 p-2 bg-second w-100 text-white justify-content-center fs-5">
    <strong>Total transaction:</strong> <%= number_to_currency(@total_transactions) %>
  </div>
<% end %>

<div id="transactions">
  <% @recent_transactions.each do |transaction| %>
  <% if can? :read, transaction %>
    <%= link_to transaction do %>
      <div class="card-1">
        <%= render transaction %>
      </div>
    <% end %>
  <% end %>
  <% end %>
</div>

<div class="d-flex gap-3">
  <%= link_to "New category", new_category_path, class: "btn bg-first text-white w-50" %>
  <%= link_to "New transaction", new_transaction_path, class: "btn bg-second text-white w-50" %>
</div>

app/views/transactions/new.html.erb
<%= render "form", transaction: @transaction %>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="mx-4">
  <%= render @transaction %>

  <% if can? :update, @transaction %>
    <%= link_to "Edit this transaction", edit_transaction_path(@transaction), hidden: true %> 
  <% end %>

  <%= link_to "Back to transactions", transactions_path, hidden: true %>
  <%#= link_to('', transactions_path(@transaction), :class => "chevron-down") %>

  <% if can? :destroy, @transaction %>
    <%= button_to "Destroy this transaction", @transaction, method: :delete, hidden: true %>
  <% end %>
</div>